import { id, passwordHash, verifyPassword } from './seed.js';
import type { AppState, Booking, BookingStatus, Exam, Gig, Question, Role, Teacher, User } from './types.js';

const banglaDigits = new Intl.NumberFormat('bn-BD');
export const currency = (amount: number) => `৳${banglaDigits.format(amount)}`;
export const publicUser = (user: User) => ({ id: user.id, email: user.email, role: user.role, name: user.name, profile: user.profile });
export const publicTeacher = (state: AppState, teacher: Teacher) => ({ ...teacher, user: publicUser(requireUser(state, teacher.userId)), gigs: state.gigs.filter(g => g.teacherId === teacher.id && g.active) });
export function requireUser(state: AppState, userId: string) { const user = state.users.find(u => u.id === userId); if (!user) throw new DomainError('ব্যবহারকারী পাওয়া যায়নি।', 404); return user; }
export class DomainError extends Error { constructor(message: string, public status = 400) { super(message); } }
export const cleanText = (value: unknown, label: string, max = 2000) => { if (typeof value !== 'string' || !value.trim() || value.trim().length > max) throw new DomainError(`${label} সঠিকভাবে দিন।`); return value.trim(); };
export const requireRole = (user: User, roles: Role[]) => { if (!roles.includes(user.role)) throw new DomainError('এই কাজের অনুমতি আপনার নেই।', 403); };

export function authenticate(state: AppState, email: unknown, password: unknown) {
  const normalized = cleanText(email, 'ইমেইল', 120).toLowerCase(); const pass = cleanText(password, 'পাসওয়ার্ড', 200);
  const user = state.users.find(u => u.email === normalized && u.active);
  if (!user || !verifyPassword(pass, user.passwordHash)) throw new DomainError('ইমেইল বা পাসওয়ার্ড সঠিক নয়।', 401);
  return publicUser(user);
}
export function register(state: AppState, input: Record<string, unknown>) {
  const name = cleanText(input.name, 'নাম', 100); const email = cleanText(input.email, 'ইমেইল', 120).toLowerCase(); const password = cleanText(input.password, 'পাসওয়ার্ড', 200); const role = input.role as Role;
  if (!['STUDENT','TEACHER','PARENT'].includes(role)) throw new DomainError('সঠিক ভূমিকা নির্বাচন করুন।');
  if (!/^\S+@\S+\.\S+$/.test(email)) throw new DomainError('সঠিক ইমেইল দিন।');
  if (password.length < 6) throw new DomainError('পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।');
  if (state.users.some(u => u.email === email)) throw new DomainError('এই ইমেইল দিয়ে ইতোমধ্যে নিবন্ধন করা আছে।', 409);
  const user: User = { id: id('user'), email, passwordHash: passwordHash(password), role, name, active: true, createdAt: new Date().toISOString(), profile: {} }; state.users.push(user);
  if (role === 'TEACHER') state.teachers.push({ id: user.id, userId: user.id, headline: 'আমার প্রোফাইল সম্পন্ন করুন', bio: '', education: '', institution: '', subjects: [], skills: [], experienceYears: 0, languages: ['বাংলা'], location: '', hourlyRate: 0, rating: 0, reviewCount: 0, classes: 0, students: 0, verified: false, verificationStatus: 'PENDING', level: 'নতুন শিক্ষক', availability: {}, blockedDates: [], demoUrl: '', profileViews: 0, gigViews: 0, responseRate: 100, cancellationRate: 0 });
  state.notifications.push({ id: id('notification'), userId: user.id, type: 'WELCOME', title: 'শিখকে স্বাগতম', body: 'আপনার প্রোফাইল সম্পন্ন করে শেখা বা পড়ানো শুরু করুন।', href: '/dashboard', createdAt: new Date().toISOString() });
  return publicUser(user);
}

export function findTeachers(state: AppState, query: Record<string, unknown>) {
  const text = String(query.q ?? '').trim().toLowerCase(); const subject = String(query.subject ?? ''); const level = String(query.level ?? ''); const maxPrice = Number(query.maxPrice ?? 0); const verified = query.verified === 'true'; const minRating = Number(query.rating ?? 0);
  const candidates = state.teachers.filter(t => { const user = requireUser(state, t.userId); const haystack = [user.name,t.headline,t.bio,t.subjects.join(' '),t.skills.join(' '),...state.gigs.filter(g=>g.teacherId===t.id).flatMap(g=>[g.title,g.topic])].join(' ').toLowerCase(); return (!text || haystack.includes(text)) && (!subject || t.subjects.includes(subject)) && (!level || state.gigs.some(g=>g.teacherId===t.id && g.level === level)) && (!maxPrice || t.hourlyRate <= maxPrice) && (!minRating || t.rating >= minRating) && (!verified || t.verified); });
  const page = Math.max(1, Number(query.page ?? 1)); const perPage = Math.min(24, Math.max(1, Number(query.perPage ?? 12))); const sorted = candidates.sort((a,b) => score(b) - score(a));
  return { items: sorted.slice((page-1)*perPage, page*perPage).map(t=>publicTeacher(state,t)), total: sorted.length, page, perPage };
}
function score(t: Teacher) { return t.rating * 25 + t.experienceYears * 3 + (t.verified ? 12 : 0) + t.responseRate / 10 - t.cancellationRate; }
export function matchTeachers(state: AppState, input: Record<string, unknown>) {
  const subject = String(input.subject ?? ''); const topic = String(input.topic ?? ''); const level = String(input.level ?? ''); const budget = Number(input.budget ?? 0); const language = String(input.language ?? '');
  return state.teachers.map(t => { let points = score(t); if (subject && t.subjects.includes(subject)) points += 100; if (topic && t.skills.includes(topic)) points += 60; if (level && state.gigs.some(g => g.teacherId === t.id && g.level === level)) points += 35; if (budget && t.hourlyRate <= budget) points += 30; if (language && t.languages.includes(language)) points += 15; return { ...publicTeacher(state,t), matchScore: Math.round(points) }; }).filter(t => !subject || t.subjects.includes(subject)).sort((a,b) => b.matchScore-a.matchScore).slice(0, 12);
}
export function updateTeacher(state: AppState, actor: User, input: Record<string, unknown>) { requireRole(actor,['TEACHER']); const teacher = state.teachers.find(t=>t.userId===actor.id); if (!teacher) throw new DomainError('শিক্ষক প্রোফাইল পাওয়া যায়নি।',404); const allowed = ['headline','bio','education','institution','location','demoUrl','hourlyRate','sessionPrice','subjects','skills','languages','availability','blockedDates','isLive','lastSeenAt']; for (const key of allowed) if (input[key] !== undefined) (teacher as unknown as Record<string,unknown>)[key] = input[key]; return teacher; }
export function createGig(state: AppState, actor: User, input: Record<string, unknown>) { requireRole(actor,['TEACHER']); const teacher = state.teachers.find(t=>t.userId===actor.id); if (!teacher) throw new DomainError('শিক্ষক প্রোফাইল পাওয়া যায়নি।'); const title=cleanText(input.title,'গিগের শিরোনাম',160), subject=cleanText(input.subject,'বিষয়',80); const basicPrice=Number(input.price); if (!Number.isFinite(basicPrice)||basicPrice<1) throw new DomainError('সঠিক মূল্য দিন।'); const gig: Gig={ id:id('gig'),teacherId:teacher.id,title,description:cleanText(input.description,'বর্ণনা'),subject,topic:cleanText(input.topic,'টপিক',80),level:cleanText(input.level,'শিক্ষার স্তর',80),language:'বাংলা',tags:[subject],demoUrl:teacher.demoUrl,includes:['লাইভ ক্লাস','ক্লাস নোট'],requirements:'শেখার আগ্রহ সঙ্গে রাখুন।',faqs:[],active:true,createdAt:new Date().toISOString(),packages:[{id:id('package'),name:'বেসিক',classes:1,duration:60,price:basicPrice,features:['১টি লাইভ ক্লাস','ক্লাস নোট']},{id:id('package'),name:'স্ট্যান্ডার্ড',classes:5,duration:60,price:basicPrice*4,features:['৫টি লাইভ ক্লাস','ক্লাস নোট','ফিডব্যাক']},{id:id('package'),name:'প্রিমিয়াম',classes:10,duration:60,price:basicPrice*7,features:['১০টি লাইভ ক্লাস','পরীক্ষা','ফিডব্যাক']}]}; state.gigs.push(gig); return gig; }

export function createBooking(state: AppState, actor: User, input: Record<string, unknown>) { requireRole(actor,['STUDENT']); const gig = state.gigs.find(g => g.id === input.gigId && g.active); if (!gig) throw new DomainError('গিগটি পাওয়া যায়নি।',404); const pack = gig.packages.find(p => p.id === input.packageId); if (!pack) throw new DomainError('প্যাকেজটি সঠিক নয়।'); const date=cleanText(input.date,'তারিখ',20), time=cleanText(input.time,'সময়',20); if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) throw new DomainError('তারিখটি সঠিক নয়।'); const teacher=state.teachers.find(t=>t.id===gig.teacherId)!; if (teacher.blockedDates.includes(date)) throw new DomainError('এই তারিখে শিক্ষক উপলভ্য নন।'); if (state.bookings.some(b=>b.teacherId===teacher.id && b.date===date && b.time===time && !['CANCELLED','REFUNDED'].includes(b.status))) throw new DomainError('এই সময়ের স্লটটি ইতোমধ্যে বুক করা হয়েছে।',409); const booking: Booking={id:id('booking'),studentId:actor.id,teacherId:teacher.id,gigId:gig.id,packageId:pack.id,date,time,price:pack.price,status:'PENDING',history:[{status:'PENDING',at:new Date().toISOString(),note:'ডেমো পেমেন্টের অপেক্ষায়'}],createdAt:new Date().toISOString()}; state.bookings.push(booking); return booking; }
export function createProblemSession(state: AppState, actor: User, input: Record<string, unknown>) { requireRole(actor,['STUDENT']); const teacherId = cleanText(input.teacherId, 'শিক্ষকের আইডি', 120); const teacher = state.teachers.find(t => t.id === teacherId); if (!teacher) throw new DomainError('শিক্ষক পাওয়া যায়নি।',404); const date = cleanText(input.date, 'তারিখ', 20); const time = cleanText(input.time, 'সময়', 20); const price = Number(input.price ?? teacher.sessionPrice ?? teacher.hourlyRate); if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) throw new DomainError('তারিখটি সঠিক নয়।'); if (!Number.isFinite(price) || price < 1) throw new DomainError('সঠিক সেশন ফি দিন।'); const ts = new Date(`${date}T00:00:00`); const dayName = ['শনিবার','রবিবার','সোমবার','মঙ্গলবার','বুধবার','বৃহস্পতিবার','শুক্রবার'][ts.getDay()]; const slots = teacher.availability[dayName] || Object.values(teacher.availability).flat(); if (!slots.includes(time)) throw new DomainError('এই স্লটটি এখন শিক্ষক অনলাইনে উপলভ্য নেই।',409); if (teacher.blockedDates.includes(date)) throw new DomainError('এই তারিখে শিক্ষক উপলভ্য নন।'); if (state.bookings.some(b => b.teacherId === teacher.id && b.date === date && b.time === time && !['CANCELLED','REFUNDED'].includes(b.status))) throw new DomainError('এই স্লটটি ইতোমধ্যে বুক করা হয়েছে।',409); const booking: Booking = { id: id('booking'), studentId: actor.id, teacherId: teacher.id, gigId: 'problem-session', packageId: 'problem-session', date, time, price, status: 'PENDING', history: [{ status: 'PENDING', at: new Date().toISOString(), note: 'সমস্যা সমাধান সেশন বুকিং তৈরি হয়েছে' }], createdAt: new Date().toISOString() }; state.bookings.push(booking); state.notifications.push({ id: id('notification'), userId: teacher.userId, type: 'BOOKING', title: 'নতুন সমস্যা সমাধান সেশন', body: `${actor.name} আপনার জন্য একটি সেশন বুক করেছে।`, href: '/dashboard', createdAt: new Date().toISOString() }); return booking; }
export function payBooking(state: AppState, actor: User, bookingId: string) { requireRole(actor,['STUDENT']); const booking=state.bookings.find(b=>b.id===bookingId); if(!booking||booking.studentId!==actor.id) throw new DomainError('বুকিং পাওয়া যায়নি।',404); if(booking.status!=='PENDING') throw new DomainError('এই বুকিংয়ের পেমেন্ট করা যাবে না।'); const tx=`DEMO-${new Date().getFullYear()}-${String(state.payments.length+1).padStart(5,'0')}`; const at=new Date().toISOString(); booking.status='CONFIRMED'; booking.history.push({status:'CONFIRMED',at,note:'লোকাল ডেমো পেমেন্ট সম্পন্ন'}); const payment={id:id('payment'),bookingId:booking.id,studentId:actor.id,amount:booking.price,status:'PAID' as const,transactionId:tx,createdAt:at}; state.payments.push(payment); const earning=Math.round(booking.price*.8); state.ledger.push({id:id('ledger'),userId:booking.teacherId,type:'PENDING_EARNING',amount:earning,ref:booking.id,note:'নিশ্চিত ডেমো বুকিংয়ের প্রাপ্য',createdAt:at},{id:id('ledger'),userId:booking.teacherId,type:'PLATFORM_FEE',amount:-Math.round(booking.price*.2),ref:booking.id,note:'প্ল্যাটফর্ম কমিশন',createdAt:at},{id:id('ledger'),userId:actor.id,type:'PAYMENT',amount:-booking.price,ref:booking.id,note:'ডেমো পেমেন্ট',createdAt:at}); state.notifications.push({id:id('notification'),userId:actor.id,type:'BOOKING',title:'আপনার বুকিং নিশ্চিত হয়েছে',body:`${booking.date} তারিখে ক্লাসটি নিশ্চিত হয়েছে।`,href:`/booking/${booking.id}`,createdAt:at},{id:id('notification'),userId:booking.teacherId,type:'PAYMENT',title:'নতুন বুকিং নিশ্চিত হয়েছে',body:`${currency(earning)} ডেমো প্রাপ্য যোগ হয়েছে।`,href:'/dashboard',createdAt:at}); return {booking,payment,receipt:{transactionId:tx,amount:booking.price,date:at,mode:'ডেমো পেমেন্ট — শুধুমাত্র লোকাল পরীক্ষার জন্য'}}; }
export function changeBookingStatus(state: AppState, actor: User, bookingId: string, status: BookingStatus) { const booking=state.bookings.find(b=>b.id===bookingId);if(!booking)throw new DomainError('বুকিং পাওয়া যায়নি।',404); if(actor.role!=='ADMIN' && actor.id!==booking.teacherId && actor.id!==booking.studentId)throw new DomainError('এই বুকিং পরিবর্তনের অনুমতি নেই।',403); booking.status=status;booking.history.push({status,at:new Date().toISOString(),note:'স্ট্যাটাস পরিবর্তন করা হয়েছে'});return booking; }
export function wallet(state: AppState, actor: User) { requireRole(actor,['TEACHER']); const entries=state.ledger.filter(e=>e.userId===actor.id); return {entries,total:entries.filter(e=>e.type==='PENDING_EARNING').reduce((n,e)=>n+e.amount,0),pending:entries.filter(e=>e.type==='PENDING_EARNING').reduce((n,e)=>n+e.amount,0),commission:Math.abs(entries.filter(e=>e.type==='PLATFORM_FEE').reduce((n,e)=>n+e.amount,0))}; }

export function conversation(state: AppState, actor: User, otherId: string) { const other=requireUser(state,otherId); const allowed=(actor.role==='STUDENT'&&other.role==='TEACHER')||(actor.role==='TEACHER'&&other.role==='STUDENT'); if(!allowed) throw new DomainError('শুধু শিক্ষক ও শিক্ষার্থীর মধ্যে বার্তা পাঠানো যায়।',403); const key=[actor.id,otherId].sort().join(':'); return state.messages.filter(m=>m.conversationId===key); }
export function listConversations(state: AppState, actor: User) {
  const participantIds = new Set(state.messages.filter(m=>m.senderId===actor.id||m.receiverId===actor.id).map(m=>m.senderId===actor.id?m.receiverId:m.senderId));
  return [...participantIds].map(otherId => { const messages=conversation(state,actor,otherId); const last=messages[messages.length-1]; return { user: publicUser(requireUser(state,otherId)), lastMessage:last, unreadCount:messages.filter(m=>m.receiverId===actor.id&&!m.readAt).length }; }).sort((a,b)=>(b.lastMessage?.createdAt||'').localeCompare(a.lastMessage?.createdAt||''));
}
export function markConversationRead(state: AppState, actor: User, otherId: string) { const messages=conversation(state,actor,otherId); const at=new Date().toISOString(); messages.forEach(message => { const saved=state.messages.find(item=>item.id===message.id); if(saved&&saved.receiverId===actor.id&&!saved.readAt)saved.readAt=at; }); return { readAt:at, count:messages.filter(message=>message.receiverId===actor.id).length }; }
export function sendMessage(state: AppState, actor: User, otherId:string, body:unknown) { conversation(state,actor,otherId); const message={id:id('message'),conversationId:[actor.id,otherId].sort().join(':'),senderId:actor.id,receiverId:otherId,body:cleanText(body,'বার্তা',1000),createdAt:new Date().toISOString()};state.messages.push(message);state.notifications.push({id:id('notification'),userId:otherId,type:'MESSAGE',title:'নতুন বার্তা এসেছে',body:`${actor.name} আপনাকে একটি বার্তা পাঠিয়েছেন।`,href:'/messages',createdAt:message.createdAt});return message; }
function examQuestions(state: AppState, exam: Exam) { return exam.questionIds.map(qid=>state.questions.find(q=>q.id===qid)).filter((q): q is Question=>Boolean(q)); }
function teacherExam(state: AppState, actor: User, examId: string) { requireRole(actor,['TEACHER']); const exam=state.exams.find(e=>e.id===examId&&e.teacherId===actor.id); if(!exam)throw new DomainError('এই পরীক্ষা পাওয়া যায়নি।',404); return exam; }
function publicExam(state: AppState, exam: Exam) { return { ...exam, status: exam.status || (exam.active?'PUBLISHED':'DRAFT'), questions: examQuestions(state,exam).map(q=>({id:q.id,text:q.text,options:q.options,marks:q.marks})) }; }
function examInputQuestions(input: unknown, subject: string, teacherId: string) { if(!Array.isArray(input)||!input.length)throw new DomainError('কমপক্ষে একটি প্রশ্ন যোগ করুন।'); return input.map((raw,index)=>{const q=raw as Record<string,unknown>;const text=cleanText(q.text,`প্রশ্ন ${index+1}`,2000);const options=Array.isArray(q.options)?q.options.map((o)=>cleanText(o,'উত্তর বিকল্প',300)).filter(Boolean):[];const answer=Number(q.answer);if(options.length<2||!Number.isInteger(answer)||answer<0||answer>=options.length)throw new DomainError(`প্রশ্ন ${index+1}-এর উত্তর বিকল্প সঠিক নয়।`);return {id:id('question'),teacherId,subject,topic:typeof q.topic==='string'?q.topic.trim():'',difficulty:typeof q.difficulty==='string'?q.difficulty:'মাঝারি',text,options,answer,explanation:typeof q.explanation==='string'?q.explanation.trim():'',marks:Math.max(1,Number(q.marks)||1),tags:[subject]};}); }
export function createExam(state: AppState, actor: User, input: Record<string,unknown>) { requireRole(actor,['TEACHER']); const title=cleanText(input.title,'পরীক্ষার শিরোনাম',160);const subject=cleanText(input.subject,'বিষয়',80);const questions=examInputQuestions(input.questions,subject,actor.id);const now=new Date().toISOString();const status=input.publish===true?'PUBLISHED':'DRAFT';const exam:Exam={id:id('exam'),teacherId:actor.id,title,description:typeof input.description==='string'?input.description.trim():'',instructions:typeof input.instructions==='string'?input.instructions.trim():'',subject,topic:typeof input.topic==='string'?input.topic.trim():'',duration:Math.max(1,Number(input.duration)||30),passMark:Math.max(0,Number(input.passMark)||0),totalMarks:questions.reduce((n,q)=>n+q.marks,0),showAnswers:input.showAnswers!==false,status,shareToken:status==='PUBLISHED'?id('exam-link'):undefined,questionIds:questions.map(q=>q.id),active:status==='PUBLISHED',createdAt:now,updatedAt:now};state.questions.push(...questions);state.exams.push(exam);return {exam:publicExam(state,exam),sharePath:exam.shareToken?`/exam/${exam.shareToken}`:undefined}; }
export function updateExam(state: AppState, actor: User, examId: string, input: Record<string,unknown>) { const exam=teacherExam(state,actor,examId);if(input.title!==undefined)exam.title=cleanText(input.title,'পরীক্ষার শিরোনাম',160);if(input.description!==undefined)exam.description=cleanText(input.description,'বর্ণনা',4000);if(input.instructions!==undefined)exam.instructions=cleanText(input.instructions,'নির্দেশনা',4000);if(input.duration!==undefined)exam.duration=Math.max(1,Number(input.duration)||30);if(input.passMark!==undefined)exam.passMark=Math.max(0,Number(input.passMark)||0);if(input.showAnswers!==undefined)exam.showAnswers=input.showAnswers!==false;if(input.questions!==undefined){const questions=examInputQuestions(input.questions,exam.subject,actor.id);exam.questionIds=questions.map(q=>q.id);exam.totalMarks=questions.reduce((n,q)=>n+q.marks,0);state.questions.push(...questions);}exam.updatedAt=new Date().toISOString();return publicExam(state,exam); }
export function publishExam(state: AppState, actor: User, examId: string) { const exam=teacherExam(state,actor,examId);if(!exam.questionIds.length)throw new DomainError('প্রকাশের আগে প্রশ্ন যোগ করুন।');exam.status='PUBLISHED';exam.active=true;exam.shareToken??=id('exam-link');exam.updatedAt=new Date().toISOString();return {exam:publicExam(state,exam),sharePath:`/exam/${exam.shareToken}`}; }
export function setExamStatus(state: AppState, actor: User, examId: string, status: 'PUBLISHED'|'CLOSED') { const exam=teacherExam(state,actor,examId);exam.status=status;exam.active=status==='PUBLISHED';if(status==='PUBLISHED')exam.shareToken??=id('exam-link');exam.updatedAt=new Date().toISOString();return exam; }
export function duplicateExam(state: AppState, actor: User, examId: string) { const source=teacherExam(state,actor,examId);const sourceQuestions=examQuestions(state,source);const now=new Date().toISOString();const questions=sourceQuestions.map(q=>({...q,id:id('question'),teacherId:actor.id}));const exam:Exam={...structuredClone(source),id:id('exam'),title:`${source.title} (কপি)`,status:'DRAFT',active:false,shareToken:undefined,questionIds:questions.map(q=>q.id),createdAt:now,updatedAt:now};state.questions.push(...questions);state.exams.push(exam);return publicExam(state,exam); }
export function deleteExam(state: AppState, actor: User, examId: string) { const exam=teacherExam(state,actor,examId);if(state.attempts.some(a=>a.examId===exam.id))throw new DomainError('ফলাফল থাকা পরীক্ষা মুছে ফেলা যাবে না। আগে পরীক্ষা বন্ধ করুন।',409);state.exams=state.exams.filter(item=>item.id!==exam.id);state.questions=state.questions.filter(question=>!exam.questionIds.includes(question.id));return {deleted:true,id:exam.id}; }
export function listTeacherExams(state: AppState, actor: User) { requireRole(actor,['TEACHER']);return state.exams.filter(e=>e.teacherId===actor.id).map(exam=>{const attempts=state.attempts.filter(a=>a.examId===exam.id);const scores=attempts.map(a=>a.percentage??(a.total?a.score/a.total*100:0));return {...publicExam(state,exam),questions:exam.questionIds.length,questionCount:exam.questionIds.length,participants:attempts.length,averageScore:scores.length?scores.reduce((n,s)=>n+s,0)/scores.length:0,highestScore:scores.length?Math.max(...scores):0,lowestScore:scores.length?Math.min(...scores):0,sharePath:exam.shareToken?`/exam/${exam.shareToken}`:undefined};}); }
export function teacherExamResults(state: AppState, actor: User, examId: string) { const exam=teacherExam(state,actor,examId);return state.attempts.filter(a=>a.examId===exam.id).map(attempt=>({ ...attempt,student:publicUser(requireUser(state,attempt.studentId)) })); }
export function getExamForStudent(state: AppState, tokenOrId: string) { const exam=state.exams.find(e=>(e.shareToken===tokenOrId||e.id===tokenOrId)&&((e.status|| (e.active?'PUBLISHED':'DRAFT'))==='PUBLISHED')&&e.active);if(!exam)throw new DomainError('পরীক্ষাটি পাওয়া যায়নি বা বন্ধ আছে।',404);return publicExam(state,exam); }
export function submitExam(state: AppState, actor: User, examId:string, answers: Record<string,unknown>) { requireRole(actor,['STUDENT']);const exam=state.exams.find(e=>e.id===examId&&e.active&&(e.status===undefined||e.status==='PUBLISHED'));if(!exam)throw new DomainError('পরীক্ষাটি পাওয়া যায়নি।',404);if(state.attempts.some(a=>a.examId===examId&&a.studentId===actor.id))throw new DomainError('এই পরীক্ষা আপনি ইতোমধ্যে জমা দিয়েছেন।',409); const questions=examQuestions(state,exam); const normalized:Record<string,number>={};let marks=0;let correctCount=0;let unansweredCount=0;for(const q of questions){const raw=answers[q.id];const a=Number.isInteger(Number(raw))?Number(raw):-1;normalized[q.id]=a;if(a<0){unansweredCount++;continue;}if(a===q.answer){marks+=q.marks;correctCount++;}}const total=questions.reduce((n,q)=>n+q.marks,0);const incorrectCount=questions.length-correctCount-unansweredCount;const percentage=total?Number((marks/total*100).toFixed(2)):0;const submittedAt=new Date().toISOString();const attempt={id:id('attempt'),examId,studentId:actor.id,answers:normalized,score:marks,total,percentage,correctCount,incorrectCount,unansweredCount,passed:exam.passMark>0?percentage>=exam.passMark:true,submittedAt,createdAt:submittedAt};state.attempts.push(attempt);state.notifications.push({id:id('notification'),userId:actor.id,type:'EXAM',title:'পরীক্ষার ফল প্রকাশিত হয়েছে',body:`আপনি ${marks}/${total} পেয়েছেন।`,href:'/exams',createdAt:submittedAt});return attempt; }
export function createReview(state: AppState, actor: User, input:Record<string,unknown>) { requireRole(actor,['STUDENT']); const booking=state.bookings.find(b=>b.id===input.bookingId&&b.studentId===actor.id);if(!booking)throw new DomainError('বুকিং পাওয়া যায়নি।',404);if(!['COMPLETED','CONFIRMED'].includes(booking.status))throw new DomainError('ক্লাস শেষ হলে রিভিউ দিতে পারবেন।');if(state.reviews.some(r=>r.bookingId===booking.id))throw new DomainError('এই ক্লাসের রিভিউ ইতোমধ্যে দেওয়া হয়েছে।',409);const rating=Number(input.rating);if(!Number.isInteger(rating)||rating<1||rating>5)throw new DomainError('১ থেকে ৫-এর মধ্যে রেটিং দিন।');const review={id:id('review'),bookingId:booking.id,studentId:actor.id,teacherId:booking.teacherId,rating,comment:cleanText(input.comment,'রিভিউ',600),createdAt:new Date().toISOString()};state.reviews.push(review);const teacher=state.teachers.find(t=>t.id===booking.teacherId)!;const reviews=state.reviews.filter(r=>r.teacherId===teacher.id);teacher.reviewCount=reviews.length;teacher.rating=Number((reviews.reduce((n,r)=>n+r.rating,0)/reviews.length).toFixed(1));return review; }
