import { type ReactNode, useState } from 'react';
import { post } from './api';
import type { Gig, Teacher, User } from './models';

export const money = (n:number) => `৳${new Intl.NumberFormat('bn-BD').format(n)}`;
export const bn = (n:number) => new Intl.NumberFormat('bn-BD').format(n);
export const shortDate = (v:string) => new Intl.DateTimeFormat('bn-BD',{dateStyle:'medium'}).format(new Date(v));
export const go = (to:string) => { location.hash=to; window.dispatchEvent(new HashChangeEvent('hashchange')); };
export function Avatar({name,size='md'}:{name:string;size?:'sm'|'md'|'lg'}) { return <span className={`avatar ${size}`}>{name.trim().slice(0,1)}</span>; }

export function Toast({message,onClose}:{message:string;onClose:()=>void}) { return <div className="toast" role="status"><span>{message}</span><button aria-label="বার্তাটি বন্ধ করুন" onClick={onClose}>×</button></div>; }
export function Shell({user,children,onLogout}:{user:User|null;children:ReactNode;onLogout:()=>void}) { const [open,setOpen]=useState(false); const dashboard=user?'/dashboard':'/login';return <><header className="topbar"><a className="brand" href="#/" aria-label="শিক্ষক হোম"><span>T</span>শিক্ষক</a><nav className={open?'open':''}><a href="#/search">শিক্ষক খুঁজুন</a><a href="#/gigs">জনপ্রিয় গিগ</a><a href="#/problems">সমস্যা সমাধান</a>{user&&<a href="#/exams">পরীক্ষা</a>}</nav><div className="head-actions">{user?<><button className="icon-btn" aria-label="নোটিফিকেশন" onClick={()=>go('/notifications')}>🔔</button><button className="user-pill" onClick={()=>go(dashboard)}><Avatar name={user.name} size="sm"/><span>{user.name}</span></button><button className="quiet-btn logout" onClick={onLogout}>লগআউট</button></>:<><a className="quiet-btn" href="#/login">লগইন</a><a className="button small" href="#/register">নিবন্ধন</a></>}</div><button className="menu-btn" onClick={()=>setOpen(!open)} aria-label="মেনু খুলুন">☰</button></header><main>{children}</main>{user&&<MobileNav user={user}/>}<footer><div className="brand"><span>T</span>শিক্ষক</div><p>Created By Tanvir Alam Prince</p></footer></> }
function MobileNav({user}:{user:User}) { const items=user.role==='TEACHER'?[['⌂','ড্যাশবোর্ড','/dashboard'],['▣','বুকিং','/bookings'],['♙','শিক্ষার্থী','/messages'],['৳','আয়','/wallet'],['◉','প্রোফাইল','/profile']]:[['⌂','হোম','/'],['⌕','খুঁজুন','/search'],['▣','বুকিং','/bookings'],['✉','বার্তা','/messages'],['◉','প্রোফাইল','/dashboard']];return <nav className="mobile-nav">{items.map(([icon,label,href])=><a href={`#${href}`} key={label}><b>{icon}</b><small>{label}</small></a>)}</nav>}

export function TeacherCard({teacher,user,compare,onCompare}:{teacher:Teacher;user:User|null;compare:boolean;onCompare:(t:Teacher)=>void}) { void user; const [saved,setSaved]=useState(false); const favorite=async()=>{try{const r=await post<{saved:boolean}>('/favorites',{kind:'TEACHER',itemId:teacher.id});setSaved(r.saved);}catch{go('/login');}};return <article className="teacher-card"><div className="card-top"><Avatar name={teacher.user.name} size="lg"/><div className="grow"><h3>{teacher.user.name}{teacher.verified&&<em className="verified">✓ যাচাইকৃত</em>}</h3><p>{teacher.headline}</p><div className="stars">★ {teacher.rating.toFixed(1)} <small>({bn(teacher.reviewCount)} রিভিউ)</small></div></div><button className="save-btn" onClick={favorite} aria-label="সংরক্ষণ করুন">{saved?'♥':'♡'}</button></div><div className="chips">{teacher.subjects.slice(0,2).map(s=><span key={s}>{s}</span>)}<span>{teacher.experienceYears} বছরের অভিজ্ঞতা</span></div><div className="card-meta"><span>{money(teacher.hourlyRate)} / ঘণ্টা</span><span>{teacher.languages.join(', ')}</span></div><div className="card-actions"><button className="quiet-btn" onClick={()=>onCompare(teacher)}>{compare?'তুলনায় আছে':'তুলনা করুন'}</button><button className="button" onClick={()=>go(`/teacher/${teacher.id}`)}>প্রোফাইল দেখুন</button></div></article> }

export function BookingModal({gig,onClose,onDone}:{gig:Gig;onClose:()=>void;onDone:(bookingId:string)=>void}) { const [pack,setPack]=useState(gig.packages[0]?.id||'');const [date,setDate]=useState(new Date(Date.now()+86400000).toISOString().slice(0,10));const [time,setTime]=useState('১৬:০০');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const chosen=gig.packages.find(p=>p.id===pack);const book=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const b=await post<{id:string}>('/bookings',{gigId:gig.id,packageId:pack,date,time});onDone(b.id);}catch(e){setError(e instanceof Error?e.message:'সমস্যা হয়েছে');}finally{setBusy(false);}};return <div className="modal-back"><section className="modal" role="dialog" aria-modal="true" aria-label="ক্লাস বুক করুন"><button className="close" onClick={onClose} aria-label="বন্ধ করুন">×</button><p className="eyebrow">লোকাল ডেমো বুকিং</p><h2>{gig.title}</h2><form onSubmit={book}><label>প্যাকেজ<select value={pack} onChange={e=>setPack(e.target.value)}>{gig.packages.map(p=><option value={p.id} key={p.id}>{p.name} — {p.classes}টি ক্লাস, {money(p.price)}</option>)}</select></label><div className="two"><label>তারিখ<input type="date" value={date} min={new Date().toISOString().slice(0,10)} onChange={e=>setDate(e.target.value)} required/></label><label>সময়<select value={time} onChange={e=>setTime(e.target.value)}><option>১০:০০</option><option>১৪:০০</option><option>১৬:০০</option><option>১৮:০০</option><option>২০:০০</option></select></label></div><div className="price-line"><span>মোট ডেমো মূল্য</span><b>{money(chosen?.price||0)}</b></div>{error&&<p className="form-error">{error}</p>}<button className="button wide" disabled={busy}>{busy?'বুকিং তৈরি হচ্ছে…':'ডেমো পেমেন্টে এগিয়ে যান'}</button><p className="help">ডেমো পেমেন্ট — শুধুমাত্র লোকাল পরীক্ষার জন্য</p></form></section></div> }

export function Empty({children}:{children:ReactNode}) { return <div className="empty"><span>◌</span><p>{children}</p></div> }
export function Loading(){return <div className="loading"><i></i>তথ্য লোড হচ্ছে…</div>}
