import { useEffect, useMemo, useState } from 'react';
import { api, put, post } from './api';
import { go, money } from './components';
import type { GigDraft, GigDraftPackage } from './models';

type Draft = GigDraft;
const steps = ['গিগের পরিচিতি', 'বিষয় ও ক্যাটাগরি', 'কী শেখাবেন', 'কার জন্য', 'ক্লাসের ধরন', 'মূল্য ও প্যাকেজ', 'অতিরিক্ত সেবা', 'ডেমো ও মিডিয়া', 'শিক্ষার্থীর প্রয়োজনীয় তথ্য', 'কী কী পাবেন', 'FAQ', 'Availability', 'Policies', 'Preview', 'Publish'];
const blankPackage = (): GigDraftPackage => ({ id: crypto.randomUUID(), name: 'নতুন প্যাকেজ', classes: 1, duration: 60, price: 500, discount: 0, validity: 30, capacity: 1, features: ['লাইভ ক্লাস'], policy: '' });

export function GigBuilder() {
  const [draft, setDraft] = useState<Draft | null>(null);
  const [step, setStep] = useState(1);
  const [saving, setSaving] = useState(false);
  const [savedAt, setSavedAt] = useState('');
  const [qualityScore, setQualityScore] = useState(0);
  const [error, setError] = useState('');
  const [published, setPublished] = useState(false);
  useEffect(() => { void api<Draft>('/teacher/gig-drafts').then(value => { setDraft(value); setQualityScore(value.qualityScore); setStep(value.step || 1); }).catch(e => setError(e.message)); }, []);
  useEffect(() => {
    if (!draft) return;
    const timer = window.setTimeout(() => { setSaving(true); void put<Draft>('/teacher/gig-drafts', { ...draft, step }).then(value => { setQualityScore(value.qualityScore); setSavedAt(new Date().toLocaleTimeString('bn-BD', { hour: '2-digit', minute: '2-digit' })); }).catch(e => setError(e.message)).finally(() => setSaving(false)); }, 700);
    return () => window.clearTimeout(timer);
  }, [draft, step]);
  const update = (patch: Partial<Draft>) => setDraft(current => current ? { ...current, ...patch, step } : current);
  const score = qualityScore;
  const preview = useMemo(() => draft ? ({ ...draft, packages: draft.packages.filter(p => p.name.trim()) }) : null, [draft]);
  if (!draft) return <section className="page section"><p className="loading">গিগ বিল্ডার প্রস্তুত হচ্ছে…</p>{error && <p className="form-error">{error}</p>}</section>;
  const next = () => { setError(''); if (step < 15) setStep(step + 1); };
  const back = () => { setError(''); if (step > 1) setStep(step - 1); };
  const publish = async () => { setError(''); try { await post(`/teacher/gig-drafts/${draft.id}/publish`); setPublished(true); } catch (e) { setError(e instanceof Error ? e.message : 'প্রকাশ করা যায়নি'); } };
  return <section className="gig-builder page">
    <div className="builder-head"><div><p className="eyebrow">শিক্ষকের সার্ভিস স্টোরফ্রন্ট</p><h1>নতুন গিগ তৈরি করুন</h1><p>ধাপে ধাপে সাজান, পাশে লাইভ প্রিভিউ দেখুন এবং যেকোনো সময় ফিরে আসুন।</p></div><div className="quality-meter"><span>গিগ মান</span><strong>{score}/১০০</strong><i><b style={{ width: `${score}%` }} /></i><small>{saving ? 'সংরক্ষণ হচ্ছে…' : savedAt ? `শেষ সংরক্ষণ ${savedAt}` : 'স্বয়ংক্রিয় সংরক্ষণ'}</small></div></div>
    <div className="builder-layout"><aside className="builder-steps">{steps.map((label, index) => <button key={label} className={step === index + 1 ? 'active' : step > index + 1 ? 'done' : ''} onClick={() => setStep(index + 1)}><b>{index + 1}</b><span>{label}</span></button>)}</aside><div className="builder-main"><div className="builder-panel"><StepContent draft={draft} update={update} step={step} /><div className="builder-actions"><button className="quiet-btn" onClick={back} disabled={step === 1}>পেছনে</button>{step < 14 && <button className="button" onClick={next}>পরের ধাপ</button>}{step === 14 && <button className="button" onClick={next}>প্রকাশের আগে যাচাই</button>}{step === 15 && <button className="button" onClick={() => void publish()}>গিগ প্রকাশ করুন</button>}</div>{error && <p className="form-error">{error}</p>}{published && <div className="success publish-success"><b>গিগ প্রকাশিত হয়েছে</b><p>এখন শিক্ষার্থীরা আপনার সার্ভিস দেখে বুকিং করতে পারবে।</p><button className="button" onClick={() => go('/dashboard')}>ড্যাশবোর্ডে ফিরুন</button></div>}</div></div><aside className="gig-preview"><p className="eyebrow">লাইভ প্রিভিউ</p>{preview && <><div className="preview-cover">{preview.media.find(m => m.cover)?.url || 'গিগ কভার'}</div><span className="preview-badge">{preview.subject || 'বিষয়'} · {preview.levels.join(', ')}</span><h2>{preview.title || 'আপনার গিগের শিরোনাম'}</h2><p>{preview.description || 'বর্ণনা লিখলে এখানে দেখা যাবে।'}</p><div className="preview-tags">{preview.tags.filter(Boolean).map(tag => <span key={tag}>{tag}</span>)}</div><div className="preview-price"><span>শুরু হচ্ছে</span><b>{money(preview.packages[0]?.price || 0)}</b></div><button className="button wide" disabled>বুকিং প্রিভিউ</button></>}</aside></div>
  </section>;
}

function StepContent({ draft, update, step }: { draft: Draft; update: (patch: Partial<Draft>) => void; step: number }) {
  const text = (key: keyof Draft, label: string, placeholder = '') => <label>{label}<input value={String(draft[key] || '')} onChange={e => update({ [key]: e.target.value })} placeholder={placeholder} /></label>;
  const list = (key: 'tags'|'levels'|'outcomes'|'includes', label: string) => <label>{label}<input value={draft[key].join(', ')} onChange={e => update({ [key]: e.target.value.split(',').map(x => x.trim()).filter(Boolean) })} placeholder="কমা দিয়ে আলাদা করুন" /><small className="help">কমা দিয়ে একাধিক যোগ করুন</small></label>;
  if (step === 1) return <><p className="eyebrow">ধাপ ১ / ১৫</p><h2>গিগের পরিচিতি</h2>{text('title', 'শিরোনাম', 'যেমন: HSC গণিতের ক্যালকুলাস সহজে শিখুন')}<label>সংক্ষিপ্ত বর্ণনা<textarea value={draft.description} onChange={e => update({ description: e.target.value })} placeholder="শিক্ষার্থী কী ফলাফল পাবেন তা স্পষ্ট করে লিখুন" /></label></>;
  if (step === 2) return <><p className="eyebrow">ধাপ ২ / ১৫</p><h2>বিষয় ও ক্যাটাগরি</h2><div className="two">{text('subject', 'বিষয়', 'গণিত')}{text('topic', 'টপিক', 'ক্যালকুলাস')}</div>{text('subtopic', 'সাবটপিক', 'ডিফারেনশিয়েশন')}{list('tags', 'সার্চ ট্যাগ')}{list('levels', 'শিক্ষার স্তর')}</>;
  if (step === 3) return <><p className="eyebrow">ধাপ ৩ / ১৫</p><h2>কী শেখাবেন</h2>{list('outcomes', 'শেখার ফলাফল')}<label>পড়ানোর ধরন<select value={draft.teachingStyle} onChange={e => update({ teachingStyle: e.target.value })}><option>উদাহরণভিত্তিক</option><option>পরীক্ষাভিত্তিক</option><option>প্রজেক্টভিত্তিক</option><option>কনসেপ্টভিত্তিক</option></select></label></>;
  if (step === 4) return <><p className="eyebrow">ধাপ ৪ / ১৫</p><h2>কার জন্য</h2>{list('levels', 'টার্গেট শিক্ষার্থী')}{text('subtopic', 'প্রয়োজনীয় পূর্বজ্ঞান', 'বেসিক বীজগণিত')}</>;
  if (step === 5) return <><p className="eyebrow">ধাপ ৫ / ১৫</p><h2>ক্লাসের ধরন</h2><div className="two"><label>ক্লাসের ধরন<select value={draft.classType} onChange={e => update({ classType: e.target.value })}><option>লাইভ ১:১</option><option>লাইভ গ্রুপ</option><option>রেকর্ডেড কোর্স</option><option>সমস্যা সমাধান</option></select></label><label>ডেলিভারি মোড<select value={draft.deliveryMode} onChange={e => update({ deliveryMode: e.target.value })}><option>অনলাইন</option><option>সশরীরে</option><option>অনলাইন ও সশরীরে</option></select></label></div><label>প্রতি ক্লাসের সময় (মিনিট)<input type="number" min="15" value={draft.duration} onChange={e => update({ duration: Number(e.target.value) })} /></label></>;
  if (step === 6) return <><p className="eyebrow">ধাপ ৬ / ১৫</p><h2>মূল্য ও প্যাকেজ</h2><label>মূল্য নির্ধারণের ধরন<select value={draft.pricingModel} onChange={e => update({ pricingModel: e.target.value })}><option value="HOURLY">ঘণ্টাভিত্তিক</option><option value="PER_CLASS">প্রতি ক্লাস</option><option value="PACKAGE">প্যাকেজ</option><option value="PROBLEM">সমস্যাভিত্তিক</option><option value="FIXED">ফিক্সড প্রজেক্ট</option><option value="CUSTOM">কাস্টম কোট</option><option value="FREE">বিনামূল্যে</option></select></label><div className="package-editor">{draft.packages.map((pack, index) => <PackageRow key={pack.id} pack={pack} onChange={value => update({ packages: draft.packages.map((p, i) => i === index ? value : p) })} onRemove={() => update({ packages: draft.packages.filter(p => p.id !== pack.id) })} />)}</div><button className="quiet-btn" onClick={() => update({ packages: [...draft.packages, blankPackage()] })}>+ প্যাকেজ যোগ করুন</button></>;
  if (step === 7) return <><p className="eyebrow">ধাপ ৭ / ১৫</p><h2>অতিরিক্ত সেবা</h2><p className="help">Advanced settings হিসেবে অতিরিক্ত সেবা যোগ করুন।</p>{draft.extras.map((extra, index) => <div className="extra-row" key={extra.id}><input value={extra.name} onChange={e => update({ extras: draft.extras.map((x, i) => i === index ? { ...x, name: e.target.value } : x) })} placeholder="সেবা, যেমন MCQ সেট" /><input type="number" value={extra.price} onChange={e => update({ extras: draft.extras.map((x, i) => i === index ? { ...x, price: Number(e.target.value) } : x) })} aria-label="অতিরিক্ত সেবার মূল্য" /><button className="danger-btn" onClick={() => update({ extras: draft.extras.filter(x => x.id !== extra.id) })}>মুছুন</button></div>)}<button className="quiet-btn" onClick={() => update({ extras: [...draft.extras, { id: crypto.randomUUID(), name: '', price: 0, quantity: 1, description: '' }] })}>+ অতিরিক্ত সেবা</button></>;
  if (step === 8) return <><p className="eyebrow">ধাপ ৮ / ১৫</p><h2>ডেমো ও মিডিয়া</h2>{text('demoUrl', 'YouTube ডেমো URL', 'https://www.youtube.com/watch?v=...')}<p className="help">YouTube API লাগবে না; URL নিরাপদভাবে embed করা হবে।</p><label>মিডিয়া URL<input placeholder="ছবি/PDF-এর public বা local URL" onChange={e => e.target.value && update({ media: [...draft.media, { id: crypto.randomUUID(), kind: 'IMAGE', url: e.target.value, caption: '', cover: draft.media.length === 0 }] })} /></label>{draft.media.map(media => <div className="media-row" key={media.id}><span>{media.kind}</span><a href={media.url} target="_blank" rel="noreferrer">{media.url}</a><button className="quiet-btn" onClick={() => update({ media: draft.media.map(m => ({ ...m, cover: m.id === media.id })) })}>কভার</button><button className="danger-btn" onClick={() => update({ media: draft.media.filter(m => m.id !== media.id) })}>মুছুন</button></div>)}</>;
  if (step === 9) return <><p className="eyebrow">ধাপ ৯ / ১৫</p><h2>শিক্ষার্থীর প্রয়োজনীয় তথ্য</h2>{draft.requirements.map((requirement, index) => <div className="requirement-row" key={requirement.id}><input value={requirement.label} onChange={e => update({ requirements: draft.requirements.map((r, i) => i === index ? { ...r, label: e.target.value } : r) })} /><label><input type="checkbox" checked={requirement.required} onChange={e => update({ requirements: draft.requirements.map((r, i) => i === index ? { ...r, required: e.target.checked } : r) })} /> আবশ্যিক</label><button className="danger-btn" onClick={() => update({ requirements: draft.requirements.filter(r => r.id !== requirement.id) })}>মুছুন</button></div>)}<button className="quiet-btn" onClick={() => update({ requirements: [...draft.requirements, { id: crypto.randomUUID(), label: '', required: false, file: false }] })}>+ তথ্য যোগ করুন</button></>;
  if (step === 10) return <><p className="eyebrow">ধাপ ১০ / ১৫</p><h2>কী কী পাবেন</h2>{list('includes', 'সেবার অন্তর্ভুক্ত বিষয়')}{draft.trial.enabled && <div className="trial-box"><label><input type="checkbox" checked={draft.trial.enabled} onChange={e => update({ trial: { ...draft.trial, enabled: e.target.checked } })} /> ট্রায়াল ক্লাস চালু</label><label><input type="checkbox" checked={draft.trial.paid} onChange={e => update({ trial: { ...draft.trial, paid: e.target.checked } })} /> পেইড ট্রায়াল</label></div>}</>;
  if (step === 11) return <><p className="eyebrow">ধাপ ১১ / ১৫</p><h2>FAQ builder</h2>{draft.faqs.map((faq, index) => <div className="faq-row" key={faq.id}><input value={faq.q} onChange={e => update({ faqs: draft.faqs.map((f, i) => i === index ? { ...f, q: e.target.value } : f) })} placeholder="প্রশ্ন" /><textarea value={faq.a} onChange={e => update({ faqs: draft.faqs.map((f, i) => i === index ? { ...f, a: e.target.value } : f) })} placeholder="উত্তর" /><button className="danger-btn" onClick={() => update({ faqs: draft.faqs.filter(f => f.id !== faq.id) })}>মুছুন</button></div>)}<button className="quiet-btn" onClick={() => update({ faqs: [...draft.faqs, { id: crypto.randomUUID(), q: '', a: '' }] })}>+ FAQ যোগ করুন</button></>;
  if (step === 12) return <><p className="eyebrow">ধাপ ১২ / ১৫</p><h2>Availability</h2><p className="help">যে দিন ও সময় আপনি ক্লাস নেন তা লিখুন।</p>{Object.entries(draft.availability).map(([day, slots]) => <div className="availability-row" key={day}><b>{day}</b><input value={slots.join(', ')} onChange={e => update({ availability: { ...draft.availability, [day]: e.target.value.split(',').map(x => x.trim()).filter(Boolean) } })} /></div>)}<button className="quiet-btn" onClick={() => update({ availability: { ...draft.availability, নতুনদিন: ['১৬:০০'] } })}>+ দিন যোগ করুন</button></>;
  if (step === 13) return <><p className="eyebrow">ধাপ ১৩ / ১৫</p><h2>Policies</h2><label>বাতিল নীতি<textarea value={draft.cancellation} onChange={e => update({ cancellation: e.target.value })} /></label><label>Reschedule নীতি<textarea value={draft.reschedule} onChange={e => update({ reschedule: e.target.value })} /></label><label>গিগ visibility<select value={draft.visibility} onChange={e => update({ visibility: e.target.value })}><option value="PUBLIC">সবার জন্য প্রকাশ্য</option><option value="UNLISTED">শুধু লিংকধারী</option></select></label></>;
  if (step === 14) return <><p className="eyebrow">ধাপ ১৪ / ১৫</p><h2>Checkout preview</h2><div className="checkout-preview"><h3>{draft.title || 'শিরোনাম অসম্পূর্ণ'}</h3><p>{draft.description || 'বর্ণনা অসম্পূর্ণ'}</p>{draft.packages.map(p => <div key={p.id}><b>{p.name}</b><span>{money(p.price)} · {p.classes}টি ক্লাস</span></div>)}</div><p className="help">কোনো তথ্য পরিবর্তন করতে বাম পাশের ধাপে ক্লিক করুন।</p></>;
  return <><p className="eyebrow">ধাপ ১৫ / ১৫</p><h2>Publish</h2><div className="publish-check"><b>প্রকাশের আগে শেষ যাচাই</b><p>মানের স্কোর: {draft.qualityScore}/১০০</p><p>{draft.qualityScore >= 70 ? 'আপনার গিগ প্রকাশের জন্য প্রস্তুত।' : 'কমপক্ষে ৭০ স্কোর পেতে বর্ণনা, ফলাফল, প্যাকেজ, FAQ এবং availability পূরণ করুন।'}</p></div></>;
}

function PackageRow({ pack, onChange, onRemove }: { pack: GigDraftPackage; onChange: (pack: GigDraftPackage) => void; onRemove: () => void }) { return <article className="package-row"><div className="package-row-head"><input value={pack.name} onChange={e => onChange({ ...pack, name: e.target.value })} /><button className="danger-btn" onClick={onRemove}>মুছুন</button></div><div className="two"><label>ক্লাস<input type="number" min="1" value={pack.classes} onChange={e => onChange({ ...pack, classes: Number(e.target.value) })} /></label><label>সময় (মিনিট)<input type="number" min="15" value={pack.duration} onChange={e => onChange({ ...pack, duration: Number(e.target.value) })} /></label><label>মূল্য<input type="number" min="0" value={pack.price} onChange={e => onChange({ ...pack, price: Number(e.target.value) })} /></label><label>ডিসকাউন্ট %<input type="number" min="0" max="90" value={pack.discount} onChange={e => onChange({ ...pack, discount: Number(e.target.value) })} /></label></div><label>ফিচার<input value={pack.features.join(', ')} onChange={e => onChange({ ...pack, features: e.target.value.split(',').map(x => x.trim()).filter(Boolean) })} /></label></article>; }
