import { useState } from 'react';
import { put } from './api';
import type { Gig, Teacher } from './models';

type ProfileProps = { teacher: Teacher; onClose: () => void; onSaved?: () => void };
const parseAvailability = (raw: string) => Object.fromEntries(raw.split(/\n|;/).map(line => line.trim()).filter(Boolean).flatMap(line => { const index = line.indexOf(':'); if (index < 0) return []; const day = line.slice(0, index).trim(); const slots = line.slice(index + 1).split(',').map(value => value.trim()).filter(Boolean); return day ? [[day, slots]] : []; }));

export function TeacherProfileEditor({ teacher, onClose, onSaved }: ProfileProps) {
  const [form, setForm] = useState({ headline: teacher.headline, bio: teacher.bio, education: teacher.education, institution: teacher.institution, location: teacher.location, hourlyRate: String(teacher.hourlyRate), sessionPrice: String(teacher.sessionPrice ?? teacher.hourlyRate), demoUrl: teacher.demoUrl, availability: Object.entries(teacher.availability || {}).map(([day, slots]) => `${day}: ${slots.join(', ')}`).join('\n') });
  const [message, setMessage] = useState('');
  const update = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }));
  const save = async (event: React.FormEvent) => { event.preventDefault(); setMessage(''); try { await put('/teacher/availability', { ...form, hourlyRate: Number(form.hourlyRate), sessionPrice: Number(form.sessionPrice), availability: parseAvailability(form.availability) }); setMessage('প্রোফাইল সফলভাবে সংরক্ষিত হয়েছে।'); onSaved?.(); } catch (error) { setMessage(error instanceof Error ? error.message : 'প্রোফাইল সংরক্ষণ করা যায়নি।'); } };
  return <div className="modal-back"><section className="modal dashboard-editor"><button className="close" onClick={onClose}>×</button><p className="eyebrow">শিক্ষক প্রোফাইল</p><h2>প্রোফাইল ও সময়সূচি সম্পাদনা</h2><form onSubmit={save}><label>শিরোনাম<input value={form.headline} onChange={event => update('headline', event.target.value)} required /></label><label>পরিচিতি<textarea value={form.bio} onChange={event => update('bio', event.target.value)} required /></label><div className="two"><label>শিক্ষা<input value={form.education} onChange={event => update('education', event.target.value)} /></label><label>প্রতিষ্ঠান<input value={form.institution} onChange={event => update('institution', event.target.value)} /></label></div><div className="two"><label>অবস্থান<input value={form.location} onChange={event => update('location', event.target.value)} /></label><label>প্রতি ঘণ্টার মূল্য<input type="number" min="1" value={form.hourlyRate} onChange={event => update('hourlyRate', event.target.value)} required /></label></div><div className="two"><label>সেশন ফি<input type="number" min="1" value={form.sessionPrice} onChange={event => update('sessionPrice', event.target.value)} required /></label><label>ডেমো ভিডিও URL<input value={form.demoUrl} onChange={event => update('demoUrl', event.target.value)} /></label></div><label>সময়সূচি<textarea rows={5} value={form.availability} onChange={event => update('availability', event.target.value)} placeholder="সোমবার: ১০:০০, ১৬:০০" /></label>{message && <p className={message.includes('সফল') ? 'success' : 'form-error'}>{message}</p>}<button className="button wide">সংরক্ষণ করুন</button></form></section></div>;
}

export function TeacherGigEditor({ gig, onClose, onSaved }: { gig: Gig; onClose: () => void; onSaved?: () => void }) {
  const [form, setForm] = useState({ title: gig.title, description: gig.description, subject: gig.subject, topic: gig.topic, level: gig.level, price: String(gig.packages[0]?.price || 0) });
  const [message, setMessage] = useState('');
  const update = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }));
  const save = async (event: React.FormEvent) => { event.preventDefault(); setMessage(''); try { await put(`/teacher/gigs/${gig.id}`, { ...form, packages: gig.packages.map((pack, index) => index === 0 ? { ...pack, price: Number(form.price) } : pack) }); setMessage('গিগ সফলভাবে সংরক্ষিত হয়েছে।'); onSaved?.(); } catch (error) { setMessage(error instanceof Error ? error.message : 'গিগ সংরক্ষণ করা যায়নি।'); } };
  return <div className="modal-back"><section className="modal dashboard-editor"><button className="close" onClick={onClose}>×</button><p className="eyebrow">গিগ সম্পাদনা</p><h2>{gig.title}</h2><form onSubmit={save}><label>শিরোনাম<input value={form.title} onChange={event => update('title', event.target.value)} required /></label><label>বর্ণনা<textarea value={form.description} onChange={event => update('description', event.target.value)} required /></label><div className="two"><label>বিষয়<input value={form.subject} onChange={event => update('subject', event.target.value)} required /></label><label>টপিক<input value={form.topic} onChange={event => update('topic', event.target.value)} required /></label></div><div className="two"><label>শিক্ষার স্তর<input value={form.level} onChange={event => update('level', event.target.value)} required /></label><label>বেসিক মূল্য<input type="number" min="1" value={form.price} onChange={event => update('price', event.target.value)} required /></label></div>{message && <p className={message.includes('সফল') ? 'success' : 'form-error'}>{message}</p>}<button className="button wide">গিগ সংরক্ষণ করুন</button></form></section></div>;
}

